export const SET_INTERCEPT_PATTERN = 'SET_INTERCEPT_PATTERN';
export const SET_INTERCEPT_MSG = 'SET_INTERCEPT_MSG';
export const CLEAR_CARD = 'CLEAR_CARD';
export const SET_INTERCEPTING = 'SET_INTERCEPTING';
