export const SET_LAUNCH_URL = 'SET_LAUNCH_URL';
export const SET_URL_PROTOCOL = 'SET_URL_PROTOCOL';
export const SET_URL_INTERCEPT_PATTERN = 'SET_URL_INTERCEPT_PATTERN';
export const SET_CHROME_PORT = 'SET_CHROME_PORT';
export const SET_INTERCEPT_PROCESSING = 'SET_INTERCEPT_PROCESSING';
