export const SET_RESPONSE_EDITOR_URL = 'SET_RESPONSE_EDITOR_URL';
export const RESPONSE_EDITOR_INTERCEPTING = 'RESPONSE_EDITOR_INTERCEPTING';
export const SET_RESPONSE_EDITOR_FUN = 'SET_RESPONSE_EDITOR_FUN';
export const SET_UPDATED_RESPONSE = 'SET_UPDATED_RESPONSE';
